
export const ThemeRoleKeys = {
  PopupBackground: "PopupBackground",
  PopupOverlay: "PopupOverlay",
  PanelSurface: "PanelSurface",
  PanelSurfaceAlt: "PanelSurfaceAlt",
  PanelBorder: "PanelBorder",
  CardBackground: "CardBackground",
  CardBorder: "CardBorder",
  CardGlow: "CardGlow",
  TextPrimary: "TextPrimary",
  TextSecondary: "TextSecondary",
  TextMuted: "TextMuted",
  TextTitle: "TextTitle",
  TextHighlight: "TextHighlight",
  AccentPrimary: "AccentPrimary",
  AccentSecondary: "AccentSecondary",
  AccentGlow: "AccentGlow",
  ButtonPrimary: "ButtonPrimary",
  ButtonPrimaryText: "ButtonPrimaryText",
  ButtonSecondary: "ButtonSecondary",
  ButtonSecondaryText: "ButtonSecondaryText",
  ButtonDanger: "ButtonDanger",
  ButtonDangerText: "ButtonDangerText",
  ButtonDisabled: "ButtonDisabled",
  ButtonDisabledText: "ButtonDisabledText",
  TabSelected: "TabSelected",
  TabUnselected: "TabUnselected",
  TabUnderline: "TabUnderline",
  BadgeBackground: "BadgeBackground",
  BadgeText: "BadgeText",
  CurrencyPanelBackground: "CurrencyPanelBackground",
  CurrencyText: "CurrencyText",
  LevelPanelBackground: "LevelPanelBackground",
  LevelText: "LevelText",
  RefreshPanelBackground: "RefreshPanelBackground",
  RefreshText: "RefreshText",
  HandlingBlockSlotBackground: "HandlingBlockSlotBackground",
  GridBackground: "GridBackground",
  GridCellEmpty: "GridCellEmpty",
  GridCellHover: "GridCellHover",
  GridCellHighlight: "GridCellHighlight",
  GridCellBorder: "GridCellBorder",
  BlockShadow: "BlockShadow",
  BlockHighlight: "BlockHighlight",
  ProgressFill: "ProgressFill",
  ProgressBack: "ProgressBack",
  ProgressText: "ProgressText",
  SuccessText: "SuccessText",
  WarningText: "WarningText",
  ErrorText: "ErrorText",
  OverlayDim: "OverlayDim",
  OverlayBlur: "OverlayBlur"
} as const;

export type ThemeRoleKey = keyof typeof ThemeRoleKeys;
